"""empty message

Revision ID: dfdf5de67964
Revises: 32f616cd20a7
Create Date: 2023-03-18 16:28:19.479905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdf5de67964'
down_revision = '32f616cd20a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['course_code'])
        batch_op.create_foreign_key(None, 'lecturers', ['lecturer_id'], ['id'])
        batch_op.drop_column('teacher')
        batch_op.drop_column('name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('matric_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('matric_no',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lecturer_id')
        batch_op.drop_column('course_code')

    # ### end Alembic commands ###
